# Generated by Django 4.2.7 on 2023-11-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextQuestionTextAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.IntegerField(choices=[(1, 'Math Expression'), (2, 'General Question')])),
                ('question', models.CharField(max_length=2048)),
                ('answer', models.CharField(max_length=2048)),
                ('date_asked', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
