# Generated by Django 4.2.7 on 2023-11-19 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_student_user'),
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textquestiontextanswer',
            options={'ordering': ['-date_asked']},
        ),
        migrations.AlterField(
            model_name='textquestiontextanswer',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Math Expression or Conversion'), (2, 'Current Events'), (3, 'Math Word Problem'), (4, 'Grammar Check'), (5, 'Summarize Text'), (6, 'Graph Images')]),
        ),
        migrations.AlterField(
            model_name='textquestiontextanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_question_test_answers', to='authentication.student'),
        ),
        migrations.CreateModel(
            name='EquationQuestionImageAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_plot', models.BooleanField()),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('date_asked', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equation_question_image_answers', to='authentication.student')),
            ],
        ),
    ]
